### ISSUE TITLE
v2.6.0 - Launch error

### ISSUE THREAD

**Issue by THEtomaso** [shlomif/PySolFC#100]
### Issue:
PySol Fan Club edition v2.6.0 crashes at startup.

### Log:
```
Traceback (most recent call last):
  File "pysol.py", line 36, in <module>
  File "C:\projects\pysolfc\pysollib\main.py", line 30, in <module>
  File "C:\projects\pysolfc\pysollib\app.py", line 32, in <module>
  File "C:\projects\pysolfc\pysollib\images.py", line 28, in <module>
  File "C:\projects\pysolfc\pysollib\pysoltk.py", line 45, in <module>
  File "C:\projects\pysolfc\pysollib\tile\toolbar.py", line 29, in <module>
  File "C:\projects\pysolfc\pysollib\ui\tktile\menubar.py", line 7, in <module>
  File "C:\projects\pysolfc\pysollib\hint.py", line 36, in <module>
  File "C:\projects\pysolfc\pysollib\util.py", line 26, in <module>
ImportError: No module named 'site'
```

(Win8.1Pro,x64)

**Comment by kingjon3377** [comment]
I see a related crash at startup on Mac OS X Sierra. It shows a dialog box saying "**PySolFC Error**" with buttons "Open Console" and "Terminate" (and no other text); if I invoke the PySolFC binary embedded in the `.app` directly from the command line, the following stack trace is printed to the console:

```
Traceback (most recent call last):
  File "/Users/kingjon/Downloads/PySolFC.app/Contents/Resources/__boot__.py", line 386, in <module>
    _run()
  File "/Users/kingjon/Downloads/PySolFC.app/Contents/Resources/__boot__.py", line 370, in _run
    exec(compile(source, path, 'exec'), globals(), globals())
  File "/Users/kingjon/Downloads/PySolFC.app/Contents/Resources/pysol.py", line 41, in <module>
    sys.exit(main(sys.argv))
  File "pysollib/main.pyc", line 414, in main
  File "pysollib/main.pyc", line 195, in pysol_init
  File "pysollib/util.pyc", line 106, in __init__
AttributeError: module 'site' has no attribute 'PREFIXES'
2019-02-14 19:16:04.532 PySolFC[64098:772602] PySolFC Error
```

**Comment by shlomif** [comment]
Thanks for the report. @Programator2 : any idea how we can include https://docs.python.org/3/library/site.html in the windows installer? The macOS error is more strange because https://docs.python.org/3/library/site.html clearly specifies a PREFIX var.

**Comment by Programator2** [comment]
`site` module is explicitly excluded by `py2exe` (see `windows_excludes` in `py2exe/hook.py`). Presumably in older Python versions it wasn't part of the Windows Python distribution. However, I see that it's present in 3.4, which is used to create the Windows binary.

One solution that would work but is quite ugly is to manually insert the compiled `site` and `_sitebuiltins` modules into `library.zip`.

I can do it if no one comes up with a better solution.

**Comment by shlomif** [comment]
On Fri, 15 Feb 2019 14:05:46 -0800
Roderik Ploszek <notifications@github.com> wrote:

> `site` module is explicitly excluded by `py2exe` (see `windows_excludes` in
> `py2exe/hook.py`). Presumably in older Python versions it wasn't part of the
> Windows Python distribution. However, I see that it's present in 3.4, which
> is used to create the Windows binary.
> 
> One solution that would work but is quite ugly is to manually insert the
> compiled `site` and `_sitebuiltins` modules into `library.zip`.
> 
> I can do it if no one comes up with a better solution.
> 

Thanks for the info. That seems like the least bad option.

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
http://youtu.be/KxGRhd_iWuE - Never Give Up!!

Chuck Norris wrote an interpreter for a Turing-complete language using only
NOPs.
    — http://www.shlomifish.org/humour/bits/facts/Chuck-Norris/

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by kingjon3377** [comment]
> The macOS error is more strange because [docs.python.org/3/library/site.html](https://docs.python.org/3/library/site.html) clearly specifies a PREFIX var.

I dug through the Travis log to find out how the `.app` was built, and found a "stripped-down" `site.py` in [the py2app source code](https://bitbucket.org/ronaldoussoren/py2app/src/default/py2app/apptemplate/lib/site.py), which does not contain the string "prefix" at all.

**Comment by KarolS** [comment]
I just had the same problem. I recommend removing the Windows installer download from Sourceforge until the problem is fixed.

**Comment by shlomif** [comment]
@KarolS : hi, I made the 2.4.0 installer the default for now for windows.

**Comment by shlomif** [comment]
@Programator2 : for v2.6.1 I implemented a workaround for importing site in https://github.com/shlomif/PySolFC/commit/8a93f4ba1399e6a0ce38781df173cec914c3c1d0 , but now the appveyor build fails - https://help.appveyor.com/discussions/problems/20470-downloads-from-sourceforgenet-started-failing .

**Comment by Programator2** [comment]
According to the log, sourceforge.net was unavailable. Run the build again, it should work now.

**Comment by shlomif** [comment]
@Programator2 : the failure is likely not your fault but it still happens after rebuilding.

**Comment by shlomif** [comment]
Hi all! 2.6.1 hopefully fixes it - please test - https://sourceforge.net/projects/pysolfc/files/PySolFC/PySolFC-2.6.1/ - thanks!

**Comment by kingjon3377** [comment]
I can confirm that the 2.6.1 MacOS `.app` no longer crashes with the symptoms described above. (But it still doesn't start properly; I'll open a new issue with the details of that.)

**Comment by shlomif** [comment]
@kingjon3377 : thanks for the info.

**Comment by THEtomaso** [comment]
This fixes the crash under Windows too!
Well done!! :)
